// examples/web-todomvc-svelte/src/components/Footer.svelte
<script lang="ts">
import { queryDb } from '@livestore/livestore'
import { uiState$ } from '../livestore/queries.ts'
import { events, tables } from '../livestore/schema.ts'
import { store } from '../livestore/store.ts'
import type { Filter } from '../types.ts'

const { filter } = $derived(store.query(uiState$))

const setFilter = (filter: Filter) => {
  store.commit(events.uiStateSet({ filter }))
}

const incompleteCount$ = queryDb(tables.todos.count().where({ completed: false, deletedAt: null }), {
  label: 'incompleteCount',
})
</script>

<footer class="footer">
	<span class="todo-count">{store.query(incompleteCount$)} items left</span>

	<ul class="filters">
		<li>
			<a
				href="#/"
				class={filter === 'all' ? 'selected' : ''}
				onclick={() => setFilter('all')}
			>
				All
			</a>
		</li>
		<li>
			<a
				href="#/"
				class={filter === 'active' ? 'selected' : ''}
				onclick={() => setFilter('active')}
			>
				Active
			</a>
		</li>
		<li>
			<a
				href="#/"
				class={filter === 'completed' ? 'selected' : ''}
				onclick={() => setFilter('completed')}
			>
				Completed
			</a>
		</li>
	</ul>

	<button
		class="clear-completed"
		onclick={() => {
			store.commit(events.todoClearedCompleted({ deletedAt: new Date() }));
		}}
	>
		Clear completed
	</button>
</footer>

// examples/web-todomvc-sync-celld/src/components/Footer.tsx
import { queryDb } from '@livestore/livestore'
import { useCallback } from 'react'

import { uiState$ } from '../livestore/queries.ts'
import { events, tables } from '../livestore/schema.ts'
import { useAppStore } from '../livestore/store.ts'

const incompleteCount$ = queryDb(tables.todos.count().where({ completed: false, deletedAt: null }), {
  label: 'incompleteCount',
})

export const Footer = () => {
  const store = useAppStore()
  const { filter } = store.useQuery(uiState$)
  const incompleteCount = store.useQuery(incompleteCount$)
  const setFilter = useCallback(
    (filter: (typeof tables.uiState.Value)['filter']) => store.commit(events.uiStateSet({ filter })),
    [store],
  )
  const handleAllClick = useCallback(() => setFilter('all'), [setFilter])
  const handleActiveClick = useCallback(() => setFilter('active'), [setFilter])
  const handleCompletedClick = useCallback(() => setFilter('completed'), [setFilter])
  const handleClearCompleted = useCallback(
    () => store.commit(events.todoClearedCompleted({ deletedAt: new Date() })),
    [store],
  )

  return (
    <footer className="footer">
      <span className="todo-count">{incompleteCount} items left</span>
      <ul className="filters">
        <li>
          <a href="#/" className={filter === 'all' ? 'selected' : ''} onClick={handleAllClick}>
            All
          </a>
        </li>
        <li>
          <a href="#/" className={filter === 'active' ? 'selected' : ''} onClick={handleActiveClick}>
            Active
          </a>
        </li>
        <li>
          <a href="#/" className={filter === 'completed' ? 'selected' : ''} onClick={handleCompletedClick}>
            Completed
          </a>
        </li>
      </ul>
      <button type="button" className="clear-completed" onClick={handleClearCompleted}>
        Clear completed
      </button>
    </footer>
  )
}
