// examples/web-todomvc-solid/src/components/VersionBadge.tsx
import { type Component, onMount } from 'solid-js'

import { liveStoreVersion } from '@livestore/livestore'

const versionBadgeStyle = {
  position: 'fixed',
  bottom: '16px',
  right: '16px',
  background: 'rgba(0, 0, 0, 0.8)',
  'border-radius': '4px',
  padding: '4px 8px',
  'font-size': '11px',
  'font-family':
    'ui-monospace, SFMono-Regular, "SF Mono", Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  color: 'white',
  'z-index': '1000',
  'user-select': 'none',
} as const

export const VersionBadge: Component = () => {
  onMount(() => {
    console.log(`LiveStore v${liveStoreVersion}`)
  })

  return <div style={versionBadgeStyle}>v{liveStoreVersion}</div>
}

// examples/cf-chat/src/components/VersionBadge.tsx
import { useEffect } from 'react'

import { liveStoreVersion } from '@livestore/livestore'

const versionBadgeStyle = {
  position: 'fixed',
  bottom: '16px',
  right: '16px',
  background: 'rgba(0, 0, 0, 0.8)',
  borderRadius: '4px',
  padding: '4px 8px',
  fontSize: '11px',
  fontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  color: 'white',
  zIndex: 1000,
  userSelect: 'none',
} as const

export const VersionBadge = () => {
  useEffect(() => {
    console.log(`LiveStore v${liveStoreVersion}`)
  }, [])

  return <div style={versionBadgeStyle}>v{liveStoreVersion}</div>
}
