// examples/web-todomvc-sync-celld/src/components/MainSection.tsx
import { queryDb } from '@livestore/livestore'
import React from 'react'

import { uiState$ } from '../livestore/queries.ts'
import { events, tables } from '../livestore/schema.ts'
import { useAppStore } from '../livestore/store.ts'

const visibleTodos$ = queryDb(
  (get) => {
    const { filter } = get(uiState$)
    return tables.todos.where({
      deletedAt: null,
      completed: filter === 'all' ? undefined : filter === 'completed',
    })
  },
  { label: 'visibleTodos' },
)

export const MainSection: React.FC = () => {
  const store = useAppStore()

  const toggleTodo = React.useCallback(
    ({ id, completed }: typeof tables.todos.Type) =>
      store.commit(completed ? events.todoUncompleted({ id }) : events.todoCompleted({ id })),
    [store],
  )

  const visibleTodos = store.useQuery(visibleTodos$)

  const handleTodoToggle = React.useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const id = e.currentTarget.dataset.todoId
      if (!id) return
      const todo = visibleTodos.find((item) => item.id === id)
      if (todo) {
        toggleTodo(todo)
      }
    },
    [toggleTodo, visibleTodos],
  )

  const handleTodoDelete = React.useCallback(
    (e: React.MouseEvent<HTMLButtonElement>) => {
      const id = e.currentTarget.dataset.todoId
      if (!id) return
      store.commit(events.todoDeleted({ id, deletedAt: new Date() }))
    },
    [store],
  )

  return (
    <section className="main">
      <ul className="todo-list">
        {visibleTodos.map((todo) => (
          <li key={todo.id}>
            <div className="state">
              <input
                type="checkbox"
                className="toggle"
                checked={todo.completed}
                data-todo-id={todo.id}
                onChange={handleTodoToggle}
              />
              <label>{todo.text}</label>
              <button type="button" className="destroy" data-todo-id={todo.id} onClick={handleTodoDelete} />
            </div>
          </li>
        ))}
      </ul>
    </section>
  )
}

// examples/web-todomvc-svelte/src/components/MainSection.svelte
<script lang="ts">
import { queryDb } from '@livestore/livestore'
import { uiState$ } from '../livestore/queries.ts'
import { events, tables } from '../livestore/schema.ts'
import { store } from '../livestore/store.ts'

const visibleTodos$ = queryDb(
  (get) => {
    const { filter } = get(uiState$)
    return tables.todos.where({
      deletedAt: null,
      completed: filter === 'all' ? undefined : filter === 'completed',
    })
  },
  { label: 'visibleTodos' },
)
</script>

<section class="main">
	<ul class="todo-list">
		{#each store.query(visibleTodos$) as todo (todo.id)}
			<li>
				<div class="state">
					<input
						id="toggle-{todo.id}"
						type="checkbox"
						class="toggle"
						checked={todo.completed}
						onchange={() =>
							store.commit(
								todo.completed
									? events.todoUncompleted(todo)
									: events.todoCompleted(todo)
							)}
					/>
					<label for="toggle-{todo.id}">{todo.text}</label>
					<button
						aria-label="Delete"
						class="destroy"
						onclick={() =>
							store.commit(
								events.todoDeleted({ id: todo.id, deletedAt: new Date() })
							)}
					></button>
				</div>
			</li>
		{/each}
	</ul>
</section>
