// examples/web-todomvc-svelte/src/components/Header.svelte
<script lang="ts">
import { uiState$ } from '../livestore/queries.ts'
import { events } from '../livestore/schema.ts'
import { store } from '../livestore/store.ts'

const { newTodoText } = $derived(store.query(uiState$))
</script>

<header class="header">
	<h1>TodoMVC</h1>
	<input
		class="new-todo"
		placeholder="What needs to be done?"
		autofocus
		bind:value={
			() => newTodoText,
			(v) => store.commit(events.uiStateSet({ newTodoText: v }))
		}
		onkeydown={(e) => {
			if (e.key === 'Enter') {
				store.commit(
					events.todoCreated({ id: crypto.randomUUID(), text: newTodoText }),
					events.uiStateSet({ newTodoText: '' })
				);
			}
		}}
	/>
</header>

// examples/web-todomvc-sync-electric/src/components/Header.tsx
import { type ChangeEvent, type KeyboardEvent, useCallback } from 'react'

import { uiState$ } from '../livestore/queries.ts'
import { events } from '../livestore/schema.ts'
import { useAppStore } from '../livestore/store.ts'

export const Header = () => {
  const store = useAppStore()
  const { newTodoText } = store.useQuery(uiState$)

  const updatedNewTodoText = useCallback(
    (text: string) => store.commit(events.uiStateSet({ newTodoText: text })),
    [store],
  )

  const todoCreated = useCallback(
    () =>
      store.commit(
        events.todoCreated({ id: crypto.randomUUID(), text: newTodoText }),
        events.uiStateSet({ newTodoText: '' }),
      ),
    [newTodoText, store],
  )

  const handleChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => updatedNewTodoText(e.target.value),
    [updatedNewTodoText],
  )

  const handleKeyDown = useCallback(
    (e: KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') {
        todoCreated()
      }
    },
    [todoCreated],
  )

  return (
    <header className="header">
      <h1>TodoMVC</h1>
      <input
        className="new-todo"
        placeholder="What needs to be done?"
        value={newTodoText}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
      />
    </header>
  )
}
